
trigger:
  - master
variables:
  - name: agent.preferPowerShellOnContainers
    value: "True"
    
pool:
      vmImage: "windows-2019"
container:
      image: dwfmt.azurecr.io/ravimukkamaladwfmt:2
      endpoint: dwfmt

steps:
  - script: C:\UiPath\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildNumber)
    displayName: "Build the artifact"
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: drop
  - powershell: |
      Install-PackageProvider -Name NuGet -Force
      Register-PSRepository -Name UiPath -SourceLocation https://www.myget.org/F/uipath-dev/api/v2
      Install-Module -Repository UiPath -Name UiPath.Powershell -Force
      Import-Module UiPath.Powershell
      $token = Get-UiPathAuthToken -ClientId $('8DEv1AMNXczW3y4U15LL3jYf62jK93n5') -UserKey $('Skhdbztw4pSK0NATkxFuRQAJZe2xDIyWchZ4XvFTq2DEb') -AccountName $('rpawodirocjl') -CloudDeployment 'Production' -TenantName $('RPAWORLDDefault')
      Add-UiPathPackage -PackageFile $(Pipeline.Workspace)\drop\uipath-sample.1.0.$(Build.BuildNumber).nupkg -AuthToken $token
